//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/11/2016 4:49:56 PM
namespace ghostshockey.it.api.Models
{
    /// <summary>
    /// There are no comments for YearSingle in the schema.
    /// </summary>
    public partial class YearSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Year>
    {
        /// <summary>
        /// Initialize a new YearSingle object.
        /// </summary>
        public YearSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new YearSingle object.
        /// </summary>
        public YearSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new YearSingle object.
        /// </summary>
        public YearSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Year> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Year in the schema.
    /// </summary>
    /// <KeyProperties>
    /// YearID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("YearID")]
    public partial class Year : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Year object.
        /// </summary>
        /// <param name="yearID">Initial value of YearID.</param>
        /// <param name="year1">Initial value of Year1.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Year CreateYear(int yearID, string year1)
        {
            Year year = new Year();
            year.YearID = yearID;
            year.Year1 = year1;
            return year;
        }
        /// <summary>
        /// There are no comments for Property YearID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int YearID
        {
            get
            {
                return this._YearID;
            }
            set
            {
                this.OnYearIDChanging(value);
                this._YearID = value;
                this.OnYearIDChanged();
                this.OnPropertyChanged("YearID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _YearID;
        partial void OnYearIDChanging(int value);
        partial void OnYearIDChanged();
        /// <summary>
        /// There are no comments for Property Year1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Year1
        {
            get
            {
                return this._Year1;
            }
            set
            {
                this.OnYear1Changing(value);
                this._Year1 = value;
                this.OnYear1Changed();
                this.OnPropertyChanged("Year1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Year1;
        partial void OnYear1Changing(string value);
        partial void OnYear1Changed();
        /// <summary>
        /// There are no comments for Property DateStart in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<global::System.DateTimeOffset> DateStart
        {
            get
            {
                return this._DateStart;
            }
            set
            {
                this.OnDateStartChanging(value);
                this._DateStart = value;
                this.OnDateStartChanged();
                this.OnPropertyChanged("DateStart");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateStart;
        partial void OnDateStartChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateStartChanged();
        /// <summary>
        /// There are no comments for Property DateEnd in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<global::System.DateTimeOffset> DateEnd
        {
            get
            {
                return this._DateEnd;
            }
            set
            {
                this.OnDateEndChanging(value);
                this._DateEnd = value;
                this.OnDateEndChanged();
                this.OnPropertyChanged("DateEnd");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateEnd;
        partial void OnDateEndChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateEndChanged();
        /// <summary>
        /// There are no comments for Property IsCurrent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<bool> IsCurrent
        {
            get
            {
                return this._IsCurrent;
            }
            set
            {
                this.OnIsCurrentChanging(value);
                this._IsCurrent = value;
                this.OnIsCurrentChanged();
                this.OnPropertyChanged("IsCurrent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<bool> _IsCurrent;
        partial void OnIsCurrentChanging(global::System.Nullable<bool> value);
        partial void OnIsCurrentChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CategorySingle in the schema.
    /// </summary>
    public partial class CategorySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Category>
    {
        /// <summary>
        /// Initialize a new CategorySingle object.
        /// </summary>
        public CategorySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CategorySingle object.
        /// </summary>
        public CategorySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CategorySingle object.
        /// </summary>
        public CategorySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Category> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Teams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Team> Teams
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Teams == null))
                {
                    this._Teams = Context.CreateQuery<global::ghostshockey.it.api.Models.Team>(GetPath("Teams"));
                }
                return this._Teams;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Team> _Teams;
    }
    /// <summary>
    /// There are no comments for Category in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CategoryID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("CategoryID")]
    public partial class Category : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="categoryID">Initial value of CategoryID.</param>
        /// <param name="categoryTag">Initial value of CategoryTag.</param>
        /// <param name="category1">Initial value of Category1.</param>
        /// <param name="enabled">Initial value of Enabled.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Category CreateCategory(int categoryID, string categoryTag, string category1, byte enabled)
        {
            Category category = new Category();
            category.CategoryID = categoryID;
            category.CategoryTag = categoryTag;
            category.Category1 = category1;
            category.Enabled = enabled;
            return category;
        }
        /// <summary>
        /// There are no comments for Property CategoryID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int CategoryID
        {
            get
            {
                return this._CategoryID;
            }
            set
            {
                this.OnCategoryIDChanging(value);
                this._CategoryID = value;
                this.OnCategoryIDChanged();
                this.OnPropertyChanged("CategoryID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _CategoryID;
        partial void OnCategoryIDChanging(int value);
        partial void OnCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property CategoryTag in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string CategoryTag
        {
            get
            {
                return this._CategoryTag;
            }
            set
            {
                this.OnCategoryTagChanging(value);
                this._CategoryTag = value;
                this.OnCategoryTagChanged();
                this.OnPropertyChanged("CategoryTag");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _CategoryTag;
        partial void OnCategoryTagChanging(string value);
        partial void OnCategoryTagChanged();
        /// <summary>
        /// There are no comments for Property Category1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Category1
        {
            get
            {
                return this._Category1;
            }
            set
            {
                this.OnCategory1Changing(value);
                this._Category1 = value;
                this.OnCategory1Changed();
                this.OnPropertyChanged("Category1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Category1;
        partial void OnCategory1Changing(string value);
        partial void OnCategory1Changed();
        /// <summary>
        /// There are no comments for Property Enabled in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public byte Enabled
        {
            get
            {
                return this._Enabled;
            }
            set
            {
                this.OnEnabledChanging(value);
                this._Enabled = value;
                this.OnEnabledChanged();
                this.OnPropertyChanged("Enabled");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private byte _Enabled;
        partial void OnEnabledChanging(byte value);
        partial void OnEnabledChanged();
        /// <summary>
        /// There are no comments for Property Teams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::ghostshockey.it.api.Models.Team> Teams
        {
            get
            {
                return this._Teams;
            }
            set
            {
                this.OnTeamsChanging(value);
                this._Teams = value;
                this.OnTeamsChanged();
                this.OnPropertyChanged("Teams");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::ghostshockey.it.api.Models.Team> _Teams = new global::Microsoft.OData.Client.DataServiceCollection<global::ghostshockey.it.api.Models.Team>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnTeamsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::ghostshockey.it.api.Models.Team> value);
        partial void OnTeamsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ClubSingle in the schema.
    /// </summary>
    public partial class ClubSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Club>
    {
        /// <summary>
        /// Initialize a new ClubSingle object.
        /// </summary>
        public ClubSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ClubSingle object.
        /// </summary>
        public ClubSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ClubSingle object.
        /// </summary>
        public ClubSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Club> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Teams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Team> Teams
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Teams == null))
                {
                    this._Teams = Context.CreateQuery<global::ghostshockey.it.api.Models.Team>(GetPath("Teams"));
                }
                return this._Teams;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Team> _Teams;
    }
    /// <summary>
    /// There are no comments for Club in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ClubID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ClubID")]
    public partial class Club : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Club object.
        /// </summary>
        /// <param name="clubID">Initial value of ClubID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Club CreateClub(int clubID)
        {
            Club club = new Club();
            club.ClubID = clubID;
            return club;
        }
        /// <summary>
        /// There are no comments for Property ClubID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int ClubID
        {
            get
            {
                return this._ClubID;
            }
            set
            {
                this.OnClubIDChanging(value);
                this._ClubID = value;
                this.OnClubIDChanged();
                this.OnPropertyChanged("ClubID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _ClubID;
        partial void OnClubIDChanging(int value);
        partial void OnClubIDChanged();
        /// <summary>
        /// There are no comments for Property Club1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Club1
        {
            get
            {
                return this._Club1;
            }
            set
            {
                this.OnClub1Changing(value);
                this._Club1 = value;
                this.OnClub1Changed();
                this.OnPropertyChanged("Club1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Club1;
        partial void OnClub1Changing(string value);
        partial void OnClub1Changed();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
                this.OnPropertyChanged("Address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property Cap in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Cap
        {
            get
            {
                return this._Cap;
            }
            set
            {
                this.OnCapChanging(value);
                this._Cap = value;
                this.OnCapChanged();
                this.OnPropertyChanged("Cap");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Cap;
        partial void OnCapChanging(string value);
        partial void OnCapChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
                this.OnPropertyChanged("City");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property Region in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Region
        {
            get
            {
                return this._Region;
            }
            set
            {
                this.OnRegionChanging(value);
                this._Region = value;
                this.OnRegionChanged();
                this.OnPropertyChanged("Region");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Region;
        partial void OnRegionChanging(string value);
        partial void OnRegionChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
                this.OnPropertyChanged("Phone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Property Mobile in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Mobile
        {
            get
            {
                return this._Mobile;
            }
            set
            {
                this.OnMobileChanging(value);
                this._Mobile = value;
                this.OnMobileChanged();
                this.OnPropertyChanged("Mobile");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Mobile;
        partial void OnMobileChanging(string value);
        partial void OnMobileChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<int> Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _Type;
        partial void OnTypeChanging(global::System.Nullable<int> value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Tag in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Tag
        {
            get
            {
                return this._Tag;
            }
            set
            {
                this.OnTagChanging(value);
                this._Tag = value;
                this.OnTagChanged();
                this.OnPropertyChanged("Tag");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Tag;
        partial void OnTagChanging(string value);
        partial void OnTagChanged();
        /// <summary>
        /// There are no comments for Property Icon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Icon
        {
            get
            {
                return this._Icon;
            }
            set
            {
                this.OnIconChanging(value);
                this._Icon = value;
                this.OnIconChanged();
                this.OnPropertyChanged("Icon");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Icon;
        partial void OnIconChanging(string value);
        partial void OnIconChanged();
        /// <summary>
        /// There are no comments for Property Teams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::ghostshockey.it.api.Models.Team> Teams
        {
            get
            {
                return this._Teams;
            }
            set
            {
                this.OnTeamsChanging(value);
                this._Teams = value;
                this.OnTeamsChanged();
                this.OnPropertyChanged("Teams");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::ghostshockey.it.api.Models.Team> _Teams = new global::Microsoft.OData.Client.DataServiceCollection<global::ghostshockey.it.api.Models.Team>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnTeamsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::ghostshockey.it.api.Models.Team> value);
        partial void OnTeamsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for TeamSingle in the schema.
    /// </summary>
    public partial class TeamSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Team>
    {
        /// <summary>
        /// Initialize a new TeamSingle object.
        /// </summary>
        public TeamSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new TeamSingle object.
        /// </summary>
        public TeamSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new TeamSingle object.
        /// </summary>
        public TeamSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Team> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::ghostshockey.it.api.Models.CategorySingle Category
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Category == null))
                {
                    this._Category = new global::ghostshockey.it.api.Models.CategorySingle(this.Context, GetPath("Category"));
                }
                return this._Category;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ghostshockey.it.api.Models.CategorySingle _Category;
        /// <summary>
        /// There are no comments for Club in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::ghostshockey.it.api.Models.ClubSingle Club
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Club == null))
                {
                    this._Club = new global::ghostshockey.it.api.Models.ClubSingle(this.Context, GetPath("Club"));
                }
                return this._Club;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ghostshockey.it.api.Models.ClubSingle _Club;
    }
    /// <summary>
    /// There are no comments for Team in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TeamID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("TeamID")]
    public partial class Team : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Team object.
        /// </summary>
        /// <param name="teamID">Initial value of TeamID.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Team CreateTeam(int teamID, string name)
        {
            Team team = new Team();
            team.TeamID = teamID;
            team.Name = name;
            return team;
        }
        /// <summary>
        /// There are no comments for Property TeamID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int TeamID
        {
            get
            {
                return this._TeamID;
            }
            set
            {
                this.OnTeamIDChanging(value);
                this._TeamID = value;
                this.OnTeamIDChanged();
                this.OnPropertyChanged("TeamID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _TeamID;
        partial void OnTeamIDChanging(int value);
        partial void OnTeamIDChanged();
        /// <summary>
        /// There are no comments for Property ClubID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<int> ClubID
        {
            get
            {
                return this._ClubID;
            }
            set
            {
                this.OnClubIDChanging(value);
                this._ClubID = value;
                this.OnClubIDChanged();
                this.OnPropertyChanged("ClubID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _ClubID;
        partial void OnClubIDChanging(global::System.Nullable<int> value);
        partial void OnClubIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CategoryID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<int> CategoryID
        {
            get
            {
                return this._CategoryID;
            }
            set
            {
                this.OnCategoryIDChanging(value);
                this._CategoryID = value;
                this.OnCategoryIDChanged();
                this.OnPropertyChanged("CategoryID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _CategoryID;
        partial void OnCategoryIDChanging(global::System.Nullable<int> value);
        partial void OnCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::ghostshockey.it.api.Models.Category Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this._Category = value;
                this.OnCategoryChanged();
                this.OnPropertyChanged("Category");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ghostshockey.it.api.Models.Category _Category;
        partial void OnCategoryChanging(global::ghostshockey.it.api.Models.Category value);
        partial void OnCategoryChanged();
        /// <summary>
        /// There are no comments for Property Club in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::ghostshockey.it.api.Models.Club Club
        {
            get
            {
                return this._Club;
            }
            set
            {
                this.OnClubChanging(value);
                this._Club = value;
                this.OnClubChanged();
                this.OnPropertyChanged("Club");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ghostshockey.it.api.Models.Club _Club;
        partial void OnClubChanging(global::ghostshockey.it.api.Models.Club value);
        partial void OnClubChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::ghostshockey.it.api.Models.Year as global::ghostshockey.it.api.Models.YearSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ghostshockey.it.api.Models.YearSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Year> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ghostshockey.it.api.Models.YearSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ghostshockey.it.api.Models.Year as global::ghostshockey.it.api.Models.YearSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="yearID">The value of yearID</param>
        public static global::ghostshockey.it.api.Models.YearSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Year> source,
            int yearID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "YearID", yearID }
            };
            return new global::ghostshockey.it.api.Models.YearSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ghostshockey.it.api.Models.Category as global::ghostshockey.it.api.Models.CategorySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ghostshockey.it.api.Models.CategorySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Category> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ghostshockey.it.api.Models.CategorySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ghostshockey.it.api.Models.Category as global::ghostshockey.it.api.Models.CategorySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="categoryID">The value of categoryID</param>
        public static global::ghostshockey.it.api.Models.CategorySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Category> source,
            int categoryID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "CategoryID", categoryID }
            };
            return new global::ghostshockey.it.api.Models.CategorySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ghostshockey.it.api.Models.Club as global::ghostshockey.it.api.Models.ClubSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ghostshockey.it.api.Models.ClubSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Club> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ghostshockey.it.api.Models.ClubSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ghostshockey.it.api.Models.Club as global::ghostshockey.it.api.Models.ClubSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="clubID">The value of clubID</param>
        public static global::ghostshockey.it.api.Models.ClubSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Club> source,
            int clubID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ClubID", clubID }
            };
            return new global::ghostshockey.it.api.Models.ClubSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ghostshockey.it.api.Models.Team as global::ghostshockey.it.api.Models.TeamSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ghostshockey.it.api.Models.TeamSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Team> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ghostshockey.it.api.Models.TeamSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ghostshockey.it.api.Models.Team as global::ghostshockey.it.api.Models.TeamSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="teamID">The value of teamID</param>
        public static global::ghostshockey.it.api.Models.TeamSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Team> source,
            int teamID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "TeamID", teamID }
            };
            return new global::ghostshockey.it.api.Models.TeamSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Ghostshockey
{
    /// <summary>
    /// There are no comments for GhostshockeyContainer in the schema.
    /// </summary>
    public partial class GhostshockeyContainer : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new GhostshockeyContainer object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public GhostshockeyContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Years in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Year> Years
        {
            get
            {
                if ((this._Years == null))
                {
                    this._Years = base.CreateQuery<global::ghostshockey.it.api.Models.Year>("Years");
                }
                return this._Years;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Year> _Years;
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Category> Categories
        {
            get
            {
                if ((this._Categories == null))
                {
                    this._Categories = base.CreateQuery<global::ghostshockey.it.api.Models.Category>("Categories");
                }
                return this._Categories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Category> _Categories;
        /// <summary>
        /// There are no comments for Clubs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Club> Clubs
        {
            get
            {
                if ((this._Clubs == null))
                {
                    this._Clubs = base.CreateQuery<global::ghostshockey.it.api.Models.Club>("Clubs");
                }
                return this._Clubs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Club> _Clubs;
        /// <summary>
        /// There are no comments for Teams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Team> Teams
        {
            get
            {
                if ((this._Teams == null))
                {
                    this._Teams = base.CreateQuery<global::ghostshockey.it.api.Models.Team>("Teams");
                }
                return this._Teams;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ghostshockey.it.api.Models.Team> _Teams;
        /// <summary>
        /// There are no comments for Years in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToYears(global::ghostshockey.it.api.Models.Year year)
        {
            base.AddObject("Years", year);
        }
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToCategories(global::ghostshockey.it.api.Models.Category category)
        {
            base.AddObject("Categories", category);
        }
        /// <summary>
        /// There are no comments for Clubs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToClubs(global::ghostshockey.it.api.Models.Club club)
        {
            base.AddObject("Clubs", club);
        }
        /// <summary>
        /// There are no comments for Teams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToTeams(global::ghostshockey.it.api.Models.Team team)
        {
            base.AddObject("Teams", team);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""ghostshockey.it.api.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Year"">
        <Key>
          <PropertyRef Name=""YearID"" />
        </Key>
        <Property Name=""YearID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Year1"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""DateStart"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""DateEnd"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""IsCurrent"" Type=""Edm.Boolean"" />
      </EntityType>
      <EntityType Name=""Category"">
        <Key>
          <PropertyRef Name=""CategoryID"" />
        </Key>
        <Property Name=""CategoryID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""CategoryTag"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""Category1"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""Enabled"" Type=""Edm.Byte"" Nullable=""false"" />
        <NavigationProperty Name=""Teams"" Type=""Collection(ghostshockey.it.api.Models.Team)"" />
      </EntityType>
      <EntityType Name=""Club"">
        <Key>
          <PropertyRef Name=""ClubID"" />
        </Key>
        <Property Name=""ClubID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Club1"" Type=""Edm.String"" />
        <Property Name=""Address"" Type=""Edm.String"" />
        <Property Name=""Cap"" Type=""Edm.String"" />
        <Property Name=""City"" Type=""Edm.String"" />
        <Property Name=""Region"" Type=""Edm.String"" />
        <Property Name=""Phone"" Type=""Edm.String"" />
        <Property Name=""Mobile"" Type=""Edm.String"" />
        <Property Name=""Email"" Type=""Edm.String"" />
        <Property Name=""Type"" Type=""Edm.Int32"" />
        <Property Name=""Tag"" Type=""Edm.String"" />
        <Property Name=""Icon"" Type=""Edm.String"" />
        <NavigationProperty Name=""Teams"" Type=""Collection(ghostshockey.it.api.Models.Team)"" />
      </EntityType>
      <EntityType Name=""Team"">
        <Key>
          <PropertyRef Name=""TeamID"" />
        </Key>
        <Property Name=""TeamID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""ClubID"" Type=""Edm.Int32"" />
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""CategoryID"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""Category"" Type=""ghostshockey.it.api.Models.Category"">
          <ReferentialConstraint Property=""CategoryID"" ReferencedProperty=""CategoryID"" />
        </NavigationProperty>
        <NavigationProperty Name=""Club"" Type=""ghostshockey.it.api.Models.Club"">
          <ReferentialConstraint Property=""ClubID"" ReferencedProperty=""ClubID"" />
        </NavigationProperty>
      </EntityType>
    </Schema>
    <Schema Namespace=""Ghostshockey"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""GhostshockeyContainer"">
        <EntitySet Name=""Years"" EntityType=""ghostshockey.it.api.Models.Year"" />
        <EntitySet Name=""Categories"" EntityType=""ghostshockey.it.api.Models.Category"">
          <NavigationPropertyBinding Path=""Teams"" Target=""Teams"" />
        </EntitySet>
        <EntitySet Name=""Clubs"" EntityType=""ghostshockey.it.api.Models.Club"">
          <NavigationPropertyBinding Path=""Teams"" Target=""Teams"" />
        </EntitySet>
        <EntitySet Name=""Teams"" EntityType=""ghostshockey.it.api.Models.Team"">
          <NavigationPropertyBinding Path=""Category"" Target=""Categories"" />
          <NavigationPropertyBinding Path=""Club"" Target=""Clubs"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
